### ISSUE TITLE
Is this still valid?

### ISSUE THREAD

**Issue by jamesthesnake** [arlk/CurveProximityQueries.jl#9]
https://discourse.julialang.org/t/curveproximityqueries-jl-finding-collision-or-proximity-between-parametric-curves-and-convex-objects/22813

On here you use a function called "randpoly" but it doesn't seem to work on my install (says it doesn't exist). Any idea?

**Comment by arlk** [comment]
Not under this package. It's moved [here](https://github.com/arlk/ConvexBodyProximityQueries.jl#obstacle-types).
